var namespacecom_1_1sebastianwinter_1_1fridge__management_1_1core__data__base__connector_1_1items =
[
    [ "Category", "classcom_1_1sebastianwinter_1_1fridge__management_1_1core__data__base__connector_1_1items_1_1_category.html", "classcom_1_1sebastianwinter_1_1fridge__management_1_1core__data__base__connector_1_1items_1_1_category" ],
    [ "DatabaseItemBase", "classcom_1_1sebastianwinter_1_1fridge__management_1_1core__data__base__connector_1_1items_1_1_database_item_base.html", "classcom_1_1sebastianwinter_1_1fridge__management_1_1core__data__base__connector_1_1items_1_1_database_item_base" ],
    [ "NamedDatabaseItemBase", "classcom_1_1sebastianwinter_1_1fridge__management_1_1core__data__base__connector_1_1items_1_1_named_database_item_base.html", "classcom_1_1sebastianwinter_1_1fridge__management_1_1core__data__base__connector_1_1items_1_1_named_database_item_base" ]
];